<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<<<<<<< HEAD
<testsuite hostname="QA-Scheduler" failures="1" tests="5" name="com.curriculum.Copy_Current_Map" time="29.356" errors="0" timestamp="06 Nov 2018 06:42:28 GMT" skipped="0">
  <testcase classname="com.curriculum.Copy_Current_Map" name="TCED29501" time="14.543"/>
  <testcase classname="com.curriculum.Copy_Current_Map" name="TCED29502" time="0.855"/>
  <testcase classname="com.curriculum.Copy_Current_Map" name="TCED29503" time="1.042"/>
  <testcase classname="com.curriculum.Copy_Current_Map" name="TCED29504" time="4.560"/>
  <testcase classname="com.curriculum.Copy_Current_Map" name="TCED29505" time="8.356">
    <failure message="expected [Add Topic...] but found [Topic1]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Add Topic...] but found [Topic1]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.curriculum.Copy_Current_Map.TCED29505(Copy_Current_Map.java:311)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TCED29505 -->
=======
<testsuite skipped="0" hostname="AKHIL-TS" name="com.curriculum.Copy_Current_Map" tests="5" failures="0" timestamp="6 Nov 2018 09:31:39 GMT" time="36.792" errors="0">
  <testcase name="TCED29501" time="15.800" classname="com.curriculum.Copy_Current_Map"/>
  <testcase name="TCED29503" time="1.253" classname="com.curriculum.Copy_Current_Map"/>
  <testcase name="TCED29502" time="1.430" classname="com.curriculum.Copy_Current_Map"/>
  <testcase name="TCED29504" time="4.825" classname="com.curriculum.Copy_Current_Map"/>
  <testcase name="TCED29505" time="13.484" classname="com.curriculum.Copy_Current_Map"/>
>>>>>>> bdc0d566e812a87ef8ad5c213d22f5917c9e764c
</testsuite> <!-- com.curriculum.Copy_Current_Map -->
